# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"ProgressPlot": "00_jupyterplot.ipynb"}

modules = ["jupyterplot.py"]

doc_url = "https://lvwerra.github.io/jupyterplot/"

git_url = "https://github.com/lvwerra/jupyterplot/tree/master/"

def custom_doc_links(name): return None
