# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"ProgressPlot": "00_jupyter_plot.ipynb"}

modules = ["jupyter_plot.py"]

doc_url = "https://lvwerra.github.io/jupyter_plot/"

git_url = "https://github.com/lvwerra/jupyter_plot/tree/master/"

def custom_doc_links(name): return None
